kind: Deployment
apiVersion: apps/v1
metadata:
  name: app1-dep
  namespace: default
  labels:
    ingressDep: app1-ingress
spec:
  replicas: 2
  selector:
    matchLabels:
      ingressDep: app1-ingress
  template:
    metadata:
      name: app1
      labels:
        ingressDep: app1-ingress
    spec:
      containers:
      - name: app1-cnt
        image: dhanunjay23230/app1:1.0.0
        ports:
        - containerPort: 80

---
kind: Service
apiVersion: v1
metadata:
  name: app1-svc
  namespace: default
spec:
  selector:
    ingressDep: app1-ingress
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    

---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: app1-ing
  namespace: default
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.k8s.io/connection: '[{"HTTPS" : 443}]'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:753369745113:certificate/a9c07550-c115-4c70-89a9-1009326eb5b5
    alb.ingress.kubernetes.io/group.name: "joindevops"
    alb.ingress.kubernetes.k8s.io/host: "app1.vrushali.online" #ingress will not create new alb for another application
spec:
  ingressClassName: alb
  rules:
  - host: "app1.vrushali.online"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: app1-svc
            port:
              number: 80

